/* GENERATED by scripts/ingest-templates.mjs — do not edit by hand.
   Re-run after adding or changing template PNGs.
   35 templates · 3 aspect ratios */
import type { GeneratedTemplate } from './registry';

export const GENERATED_TEMPLATES: readonly GeneratedTemplate[] = [
  {
    "id": "T001",
    "version": 1,
    "name": "Template T001",
    "asset": "0174e509-d2c6-422e-a26c-57d86adbc1b6.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "field-card",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "square",
        "box": {
          "x": 0.0954,
          "y": 0.0835,
          "w": 0.3957,
          "h": 0.2917
        }
      }
    ],
    "detectedZones": 4,
    "contentDensity": "medium",
    "featureCapacity": 3,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T002",
    "version": 1,
    "name": "Template T002",
    "asset": "026cdb83-1e4a-4f57-91dd-0193929be153.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "field-card",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "landscape",
        "box": {
          "x": 0.0758,
          "y": 0.1805,
          "w": 0.8485,
          "h": 0.3759
        }
      }
    ],
    "detectedZones": 5,
    "contentDensity": "high",
    "featureCapacity": 4,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T003",
    "version": 1,
    "name": "Template T003",
    "asset": "052dc99e-e008-4cbe-ad58-186cb8eeff25.png",
    "intrinsic": {
      "w": 1024,
      "h": 1536
    },
    "aspectRatio": "2:3",
    "archetype": "hero-dominant",
    "geometry": "undetected",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "any"
      }
    ],
    "detectedZones": 0,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T004",
    "version": 1,
    "name": "Template T004",
    "asset": "1473b9a9-080e-4044-928a-c7ebbc509306.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "hero-dominant",
    "geometry": "undetected",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "any"
      }
    ],
    "detectedZones": 0,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T005",
    "version": 1,
    "name": "Template T005",
    "asset": "153313c5-cdb4-4588-8f34-511b7a9ace65.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "hero-dominant",
    "geometry": "undetected",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "any"
      }
    ],
    "detectedZones": 0,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T006",
    "version": 1,
    "name": "Template T006",
    "asset": "1729fe26-34aa-4902-bc13-54f0867e3027.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "field-card",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "landscape",
        "box": {
          "x": 0.0633,
          "y": 0.1213,
          "w": 0.8708,
          "h": 0.4116
        }
      }
    ],
    "detectedZones": 5,
    "contentDensity": "high",
    "featureCapacity": 4,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T007",
    "version": 1,
    "name": "Template T007",
    "asset": "20a79789-fac4-4750-a3cc-362b443e8bce.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "hero-dominant",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "portrait",
        "box": {
          "x": 0.7014,
          "y": 0.4729,
          "w": 0.2398,
          "h": 0.3031
        }
      }
    ],
    "detectedZones": 2,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T008",
    "version": 1,
    "name": "Template T008",
    "asset": "2841fd68-68f7-4517-9ede-137e162642bb.png",
    "intrinsic": {
      "w": 1024,
      "h": 1536
    },
    "aspectRatio": "2:3",
    "archetype": "hero-dominant",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "portrait",
        "box": {
          "x": 0.0615,
          "y": 0.1126,
          "w": 0.8779,
          "h": 0.7051
        }
      }
    ],
    "detectedZones": 1,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T009",
    "version": 1,
    "name": "Template T009",
    "asset": "2fd3dcfe-cb7a-405e-b314-0d49dc3cdcb4.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "field-card",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "landscape",
        "box": {
          "x": 0.5009,
          "y": 0.1812,
          "w": 0.434,
          "h": 0.2924
        }
      }
    ],
    "detectedZones": 4,
    "contentDensity": "medium",
    "featureCapacity": 3,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T010",
    "version": 1,
    "name": "Template T010",
    "asset": "30f05112-ec41-455e-b4d8-a4a8edbc6e5e.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "hero-dominant",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "square",
        "box": {
          "x": 0.0508,
          "y": 0.0335,
          "w": 0.6898,
          "h": 0.577
        }
      }
    ],
    "detectedZones": 2,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T011",
    "version": 1,
    "name": "Template T011",
    "asset": "46a558f3-46d9-47aa-add6-2aa20bc8b0e1.png",
    "intrinsic": {
      "w": 1024,
      "h": 1536
    },
    "aspectRatio": "2:3",
    "archetype": "hero-dominant",
    "geometry": "undetected",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "any"
      }
    ],
    "detectedZones": 0,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T012",
    "version": 1,
    "name": "Vivid Studio",
    "asset": "482fec91-41d2-481e-9a4b-7eea6810e003.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "field-card",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "landscape",
        "box": {
          "x": 0.0731,
          "y": 0.1056,
          "w": 0.4207,
          "h": 0.2518
        }
      }
    ],
    "detectedZones": 7,
    "contentDensity": "high",
    "featureCapacity": 4,
    "styleTags": [
      "vivid",
      "modern",
      "3d",
      "bright"
    ],
    "reviewed": true
  },
  {
    "id": "T013",
    "version": 1,
    "name": "Organic Clay",
    "asset": "4f490475-8362-4dd4-a3ea-45ef637f4ba0.png",
    "intrinsic": {
      "w": 941,
      "h": 1672
    },
    "aspectRatio": "9:16",
    "archetype": "hero-dominant",
    "geometry": "undetected",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "any"
      }
    ],
    "detectedZones": 0,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [
      "earthy",
      "calm",
      "botanical",
      "premium"
    ],
    "reviewed": true
  },
  {
    "id": "T014",
    "version": 1,
    "name": "Template T014",
    "asset": "5a72c4eb-ad08-4974-b4a9-565a8ad3e212.png",
    "intrinsic": {
      "w": 1024,
      "h": 1536
    },
    "aspectRatio": "2:3",
    "archetype": "hero-dominant",
    "geometry": "undetected",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "any"
      }
    ],
    "detectedZones": 0,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T015",
    "version": 1,
    "name": "Template T015",
    "asset": "662b1b14-0204-46ab-928f-0688be60dac7.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "field-card",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "landscape",
        "box": {
          "x": 0.0722,
          "y": 0.4551,
          "w": 0.4216,
          "h": 0.2625
        }
      }
    ],
    "detectedZones": 4,
    "contentDensity": "medium",
    "featureCapacity": 3,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T016",
    "version": 1,
    "name": "Template T016",
    "asset": "8b8389be-ecb2-42ce-acc4-0907573a2143.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "field-card",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "landscape",
        "box": {
          "x": 0.0223,
          "y": 0.0193,
          "w": 0.9545,
          "h": 0.3894
        }
      }
    ],
    "detectedZones": 6,
    "contentDensity": "high",
    "featureCapacity": 4,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T017",
    "version": 1,
    "name": "Template T017",
    "asset": "8bb3776f-9b26-44ca-bc44-a89feabf400c.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "field-card",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "square",
        "box": {
          "x": 0.5062,
          "y": 0.3524,
          "w": 0.4082,
          "h": 0.2932
        }
      }
    ],
    "detectedZones": 4,
    "contentDensity": "medium",
    "featureCapacity": 3,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T018",
    "version": 1,
    "name": "Template T018",
    "asset": "90139b2c-b902-473d-a637-55bfaaf397cb.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "hero-dominant",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "landscape",
        "box": {
          "x": 0.0419,
          "y": 0.03,
          "w": 0.7299,
          "h": 0.4836
        }
      }
    ],
    "detectedZones": 2,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T019",
    "version": 1,
    "name": "Template T019",
    "asset": "90f94836-a9b9-46b8-8a31-e7dfdc92477a.png",
    "intrinsic": {
      "w": 941,
      "h": 1672
    },
    "aspectRatio": "9:16",
    "archetype": "hero-dominant",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "portrait",
        "box": {
          "x": 0.0606,
          "y": 0.0502,
          "w": 0.8789,
          "h": 0.6728
        }
      }
    ],
    "detectedZones": 2,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T020",
    "version": 1,
    "name": "Template T020",
    "asset": "9488435e-b867-4c29-8c00-0adc91b1db1c.png",
    "intrinsic": {
      "w": 941,
      "h": 1672
    },
    "aspectRatio": "9:16",
    "archetype": "hero-dominant",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "portrait",
        "box": {
          "x": 0.0882,
          "y": 0.0592,
          "w": 0.8204,
          "h": 0.6382
        }
      }
    ],
    "detectedZones": 1,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T021",
    "version": 1,
    "name": "Template T021",
    "asset": "a54946c8-81f5-4e4f-a6e6-474f30efd01d.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "hero-dominant",
    "geometry": "undetected",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "any"
      }
    ],
    "detectedZones": 0,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T022",
    "version": 1,
    "name": "Template T022",
    "asset": "ad5810f1-048d-4a0b-99c3-559a48013241.png",
    "intrinsic": {
      "w": 941,
      "h": 1672
    },
    "aspectRatio": "9:16",
    "archetype": "hero-dominant",
    "geometry": "undetected",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "any"
      }
    ],
    "detectedZones": 0,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T023",
    "version": 1,
    "name": "Template T023",
    "asset": "b2d5adf8-2933-4f36-84cf-8b0b30444ccc.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "hero-dominant",
    "geometry": "undetected",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "any"
      }
    ],
    "detectedZones": 0,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T024",
    "version": 1,
    "name": "Template T024",
    "asset": "bff28f1b-d935-4810-9aff-ccf52f362996.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "field-card",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "landscape",
        "box": {
          "x": 0.0392,
          "y": 0.0228,
          "w": 0.7781,
          "h": 0.48
        }
      }
    ],
    "detectedZones": 4,
    "contentDensity": "medium",
    "featureCapacity": 3,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T025",
    "version": 1,
    "name": "Template T025",
    "asset": "c44c8957-e62a-4eff-91e9-44fb206e14c8.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "hero-dominant",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "landscape",
        "box": {
          "x": 0.7398,
          "y": 0.8944,
          "w": 0.1898,
          "h": 0.0592
        }
      }
    ],
    "detectedZones": 1,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T026",
    "version": 1,
    "name": "Template T026",
    "asset": "c5418ac4-cdd5-454a-af35-d01246e165e6.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "field-card",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "landscape",
        "box": {
          "x": 0.0535,
          "y": 0.1398,
          "w": 0.8984,
          "h": 0.3966
        }
      }
    ],
    "detectedZones": 5,
    "contentDensity": "high",
    "featureCapacity": 4,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T027",
    "version": 1,
    "name": "Template T027",
    "asset": "c9db68b0-381a-448a-a63a-c2277d42ff21.png",
    "intrinsic": {
      "w": 941,
      "h": 1672
    },
    "aspectRatio": "9:16",
    "archetype": "hero-dominant",
    "geometry": "undetected",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "any"
      }
    ],
    "detectedZones": 0,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T028",
    "version": 1,
    "name": "Template T028",
    "asset": "d085dc23-1339-4f81-b845-1a240cfed0e3.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "hero-dominant",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "square",
        "box": {
          "x": 0.5802,
          "y": 0.3859,
          "w": 0.295,
          "h": 0.2439
        }
      }
    ],
    "detectedZones": 1,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T029",
    "version": 1,
    "name": "Template T029",
    "asset": "dbf91ca2-ee8a-4a7a-b294-158ffdb96be9.png",
    "intrinsic": {
      "w": 941,
      "h": 1672
    },
    "aspectRatio": "9:16",
    "archetype": "hero-dominant",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "portrait",
        "box": {
          "x": 0.1126,
          "y": 0.0813,
          "w": 0.7853,
          "h": 0.6071
        }
      }
    ],
    "detectedZones": 1,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T030",
    "version": 1,
    "name": "Template T030",
    "asset": "dd6edf43-3624-44fb-8198-fdb942b3f69d.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "field-card",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "square",
        "box": {
          "x": 0.5062,
          "y": 0.0407,
          "w": 0.369,
          "h": 0.2575
        }
      }
    ],
    "detectedZones": 3,
    "contentDensity": "medium",
    "featureCapacity": 2,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T031",
    "version": 1,
    "name": "Template T031",
    "asset": "ddf61c78-6f6b-4d3e-bc9f-51819cbde2ad.png",
    "intrinsic": {
      "w": 1122,
      "h": 1402
    },
    "aspectRatio": "4:5",
    "archetype": "field-card",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "landscape",
        "box": {
          "x": 0.1747,
          "y": 0.0471,
          "w": 0.795,
          "h": 0.3716
        }
      }
    ],
    "detectedZones": 16,
    "contentDensity": "high",
    "featureCapacity": 4,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T032",
    "version": 1,
    "name": "Template T032",
    "asset": "ecaeffe4-6066-4ae1-8216-2865ad5bfd06.png",
    "intrinsic": {
      "w": 1024,
      "h": 1536
    },
    "aspectRatio": "2:3",
    "archetype": "hero-dominant",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "landscape",
        "box": {
          "x": 0.1201,
          "y": 0.696,
          "w": 0.7607,
          "h": 0.2103
        }
      }
    ],
    "detectedZones": 1,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T033",
    "version": 1,
    "name": "Template T033",
    "asset": "fc732598-f47f-4cc3-8644-58d3da8b9e32.png",
    "intrinsic": {
      "w": 1024,
      "h": 1536
    },
    "aspectRatio": "2:3",
    "archetype": "hero-dominant",
    "geometry": "measured",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "square",
        "box": {
          "x": 0.082,
          "y": 0.1211,
          "w": 0.835,
          "h": 0.5703
        }
      }
    ],
    "detectedZones": 1,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T034",
    "version": 1,
    "name": "Template T034",
    "asset": "fe982139-74ea-41bc-942b-a5fd6d548843 (1).png",
    "intrinsic": {
      "w": 941,
      "h": 1672
    },
    "aspectRatio": "9:16",
    "archetype": "hero-dominant",
    "geometry": "undetected",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "any"
      }
    ],
    "detectedZones": 0,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  },
  {
    "id": "T035",
    "version": 1,
    "name": "Template T035",
    "asset": "fe982139-74ea-41bc-942b-a5fd6d548843.png",
    "intrinsic": {
      "w": 941,
      "h": 1672
    },
    "aspectRatio": "9:16",
    "archetype": "hero-dominant",
    "geometry": "undetected",
    "photoRegions": [
      {
        "role": "hero",
        "preferredOrientation": "any"
      }
    ],
    "detectedZones": 0,
    "contentDensity": "low",
    "featureCapacity": 1,
    "styleTags": [],
    "reviewed": false
  }
] as const;
