/* MAPCO AI foundation — contracts, validation, failure boundary and the
   architectural invariants that keep AI out of surfaces it must not touch. */
import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { resolve, join } from 'node:path';

import {
  parseAnswer, parseArtifact, parseGeneratedCopy, parseIntelligenceSnapshot,
  parseMarketingSuggestion, parseSignalSet, parseWeeklyReport, PAYLOAD_PARSERS,
  formatMicroUsd, AI_SCHEMA_VERSION,
} from '../src/packages/ai';
import { withAiFallback, shouldRenderAi, isInsufficient } from '../src/packages/ai/availability';
import { aiUnavailable, AI_DISABLED_STATUS } from '../src/packages/ai/contracts';
import { MockAiRepository } from '../src/packages/data/mock-ai-repository';
import { ok, err } from '../src/packages/data/contracts';

import { S, toJsonSchema, validate } from '../../supabase/functions/_shared/ai/schema.ts';
import {
  AI_SCHEMA_VERSION as EDGE_SCHEMA_VERSION, OUTPUT_SCHEMAS,
} from '../../supabase/functions/_shared/ai/schemas.ts';
import { ACTIONS, actionCatalogForPrompt, getExecutor, validateActionRequest }
  from '../../supabase/functions/_shared/ai/tools.ts';

const v2Root = resolve(__dirname, '..');
const repoRoot = resolve(__dirname, '..', '..');
const migrations = join(repoRoot, 'supabase', 'migrations');

const sql = (file: string): string => readFileSync(join(migrations, file), 'utf8');
const AI_MIGRATIONS = [
  '20260812000100_ai_core_foundation.sql',
  '20260812000200_ai_artifacts_and_actions.sql',
  '20260812000300_ai_context_builder.sql',
  '20260812000400_marketing_foundation.sql',
];
const allAiSql = (): string => AI_MIGRATIONS.map(sql).join('\n');

/* ═══════════════════════════════════════════════════════════════
   1. THE HOME RULE
   The dealer Home page must keep rendering its existing real data
   and must not consume anything from the AI layer.
   ═══════════════════════════════════════════════════════════════ */

describe('dealer Home stays free of AI', () => {
  const home = readFileSync(join(v2Root, 'src/apps/dealer/pages/home.ts'), 'utf8');

  it('imports nothing from the AI package', () => {
    expect(home).not.toMatch(/packages\/ai/);
  });

  it('never reads the AI repository', () => {
    expect(home).not.toContain('adapter.ai');
  });

  it('loads only the real operational sources the Home surface needs', () => {
    // Demand signals are the dealer's own presentation opens, not an AI feed —
    // the approved Home (Dealer Dashboard.dc.html) is built on them.
    expect(home).not.toContain('adapter.ai');
    expect(home).toContain('adapter.clientLinks.list(');
    expect(home).toContain('adapter.properties.list(');
  });

  it('has no hardcoded AI narrative, insight or recommendation copy', () => {
    for (const pattern of [
      /MAPCO Intelligence/i, /AI insight/i, /AI summary/i, /AI recommend/i,
      /weekly report/i, /generated by AI/i,
    ]) {
      expect(pattern.test(home)).toBe(false);
    }
  });
});

describe('no dealer or presentation surface consumes AI yet', () => {
  function walk(dir: string): string[] {
    const out: string[] = [];
    for (const name of readdirSync(dir)) {
      const full = join(dir, name);
      if (statSync(full).isDirectory()) out.push(...walk(full));
      else if (/\.ts$/.test(name)) out.push(full);
    }
    return out;
  }

  it('only the internal AI console reads adapter.ai', () => {
    const consumers = walk(join(v2Root, 'src/apps'))
      .filter((file) => /adapter\.ai\b/.test(readFileSync(file, 'utf8')))
      .map((file) => file.replace(/\\/g, '/').split('/src/apps/')[1]);
    expect(consumers).toEqual(['ai-console/main.ts']);
  });

  it('the AI console is not linked from the dealer navigation', () => {
    const shell = readFileSync(join(v2Root, 'src/apps/dealer/shell.ts'), 'utf8');
    expect(shell).not.toContain('ai-console');
  });
});

/* ═══════════════════════════════════════════════════════════════
   2. NO SECRET REACHES THE BROWSER
   ═══════════════════════════════════════════════════════════════ */

describe('provider credentials stay server-side', () => {
  function walk(dir: string): string[] {
    const out: string[] = [];
    for (const name of readdirSync(dir)) {
      const full = join(dir, name);
      if (statSync(full).isDirectory()) out.push(...walk(full));
      else if (/\.ts$/.test(name)) out.push(full);
    }
    return out;
  }

  it('no browser source mentions a provider key or a provider endpoint', () => {
    for (const file of walk(join(v2Root, 'src'))) {
      const text = readFileSync(file, 'utf8');
      expect(text).not.toContain('OPENAI_API_KEY');
      expect(text).not.toContain('api.openai.com');
      expect(text).not.toContain('VITE_OPENAI');
    }
  });

  it('the provider key is read only inside the Edge provider module', () => {
    const provider = readFileSync(
      join(repoRoot, 'supabase/functions/_shared/ai/providers/openai.ts'), 'utf8');
    expect(provider).toContain("Deno.env.get('OPENAI_API_KEY')");
    const service = readFileSync(
      join(repoRoot, 'supabase/functions/_shared/ai/service.ts'), 'utf8');
    expect(service).not.toContain('OPENAI_API_KEY');
  });
});

/* ═══════════════════════════════════════════════════════════════
   3. STRUCTURED OUTPUT
   ═══════════════════════════════════════════════════════════════ */

describe('schema DSL', () => {
  const schema = S.object({
    title: S.string({ maxLength: 10 }),
    count: S.number({ integer: true, min: 0 }),
    mode: S.enum(['a', 'b']),
    tags: S.array(S.string({ maxLength: 4 }), 2),
    note: S.string({ maxLength: 5 }),
  }, { optional: ['note'] });

  it('projects a strict JSON Schema providers can enforce', () => {
    const json = toJsonSchema(schema) as Record<string, unknown>;
    expect(json.additionalProperties).toBe(false);
    // Strict structured output requires every property to be listed.
    expect(json.required).toEqual(['title', 'count', 'mode', 'tags', 'note']);
    const properties = json.properties as Record<string, { type: unknown }>;
    expect(properties.note.type).toEqual(['string', 'null']);
    expect(properties.title.type).toBe('string');
  });

  it('accepts a valid value and strips undeclared keys', () => {
    const result = validate(schema, {
      title: 'ok', count: 3, mode: 'b', tags: ['x'], note: null,
      smuggled: 'should not survive',
    });
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value).toEqual({ title: 'ok', count: 3, mode: 'b', tags: ['x'] });
      expect('smuggled' in (result.value as object)).toBe(false);
    }
  });

  it('rejects a missing required field', () => {
    const result = validate(schema, { count: 1, mode: 'a', tags: [] });
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.errors.join(' ')).toContain('$.title');
  });

  it('rejects a wrong type and an unknown enum value', () => {
    const result = validate(schema, { title: 'x', count: 'nope', mode: 'z', tags: [] });
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.errors.join(' ')).toContain('$.count');
      expect(result.errors.join(' ')).toContain('$.mode');
    }
  });

  it('caps an over-long array and trims an over-long string', () => {
    const result = validate(schema, {
      title: 'abcdefghijklmno', count: 1, mode: 'a', tags: ['1', '2', '3', '4'],
    });
    expect(result.ok).toBe(true);
    if (result.ok) {
      const value = result.value as { title: string; tags: string[] };
      expect(value.title).toHaveLength(10);
      expect(value.tags).toHaveLength(2);
    }
  });

  it('rejects a non-object payload outright', () => {
    expect(validate(schema, 'not an object').ok).toBe(false);
    expect(validate(schema, null).ok).toBe(false);
    expect(validate(schema, [1, 2]).ok).toBe(false);
  });
});

describe('canonical output schemas', () => {
  it('every task output schema projects to a strict object schema', () => {
    for (const [name, schema] of Object.entries(OUTPUT_SCHEMAS)) {
      const json = toJsonSchema(schema) as Record<string, unknown>;
      expect(json.type, name).toBe('object');
      expect(json.additionalProperties, name).toBe(false);
    }
  });

  it('keeps the browser and Edge schema versions aligned', () => {
    expect(AI_SCHEMA_VERSION).toBe(EDGE_SCHEMA_VERSION);
  });

  it('requires evidence on every signal', () => {
    const result = validate(OUTPUT_SCHEMAS.signal_set, {
      periodLabel: '2026-08-12', summary: 'x', insufficientData: false,
      signals: [{
        id: 's1', kind: 'attention_rising',
        subject: { kind: 'area', id: 'Mohali', label: 'Mohali' },
        headline: 'h', detail: 'd', direction: 'up', magnitude: 0.5, confidence: 'medium',
        evidence: [],
      }],
    });
    expect(result.ok).toBe(false);
  });
});

/* ═══════════════════════════════════════════════════════════════
   4. CONTROLLED ACTIONS
   ═══════════════════════════════════════════════════════════════ */

describe('action catalog', () => {
  it('rejects an action name that is not in the catalog', () => {
    const result = validateActionRequest('drop_all_properties', {});
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.reason).toBe('unknown_action');
  });

  it('rejects valid-looking parameters that fail the action schema', () => {
    const result = validateActionRequest('select_properties_for_marketing', { reason: 'because' });
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.reason).toBe('invalid_params');
  });

  it('accepts and normalises a valid request', () => {
    const result = validateActionRequest('select_properties_for_marketing', {
      propertyIds: ['prop-1', 'prop-2'], reason: 'no opens in 14 days', extra: 'dropped',
    });
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.action.risk).toBe('internal');
      expect('extra' in result.params).toBe(false);
    }
  });

  it('never marks an external action as approval-free', () => {
    for (const action of Object.values(ACTIONS)) {
      if (action.risk !== 'internal') {
        const entry = actionCatalogForPrompt().find((item) => item.type === action.type)!;
        expect(entry.requiresApproval, action.type).toBe(true);
      }
    }
  });

  it('registers no executor yet, so nothing can silently run', () => {
    for (const type of Object.keys(ACTIONS)) {
      expect(getExecutor(type), type).toBeNull();
    }
  });
});

/* ═══════════════════════════════════════════════════════════════
   5. RENDER-SIDE GUARDS
   ═══════════════════════════════════════════════════════════════ */

const validSnapshot = {
  periodLabel: '2026-08-12',
  headline: 'Sector 82 drew the most attention today.',
  interpretation: 'Opens concentrated in one sector.',
  insufficientData: false,
  dataNotes: ['Presentation activity is anonymous.'],
  signals: [{
    id: 'sig-1', kind: 'attention_rising',
    subject: { kind: 'sector', id: 'Sector 82', label: 'Sector 82' },
    headline: 'Sector 82 opens rose', detail: '50 opens vs 30 last period',
    direction: 'up', magnitude: 0.8, confidence: 'high',
    evidence: [{ factPath: 'presentation.bySector[0]', metric: 'opens', value: 50, previousValue: 30 }],
  }],
  recommendations: [{
    id: 'rec-1', title: 'Lead with Sector 82 stock', reason: 'Most opened area this period.',
    subject: { kind: 'sector', id: 'Sector 82', label: 'Sector 82' },
    priority: 'now', confidence: 'medium',
    evidence: [{ factPath: 'presentation.bySector[0]', metric: 'opens', value: 50 }],
  }],
};

describe('render-side guards', () => {
  it('parses a well-formed snapshot', () => {
    const parsed = parseIntelligenceSnapshot(validSnapshot);
    expect(parsed).not.toBeNull();
    expect(parsed!.signals).toHaveLength(1);
    expect(parsed!.recommendations[0]!.priority).toBe('now');
  });

  it('returns null rather than throwing on malformed input', () => {
    for (const bad of [null, undefined, 42, 'text', [], {}, { headline: 123 }]) {
      expect(parseIntelligenceSnapshot(bad)).toBeNull();
    }
  });

  it('drops undeclared keys from a stored payload', () => {
    const parsed = parseIntelligenceSnapshot({ ...validSnapshot, injected: '<script>' })!;
    expect('injected' in parsed).toBe(false);
  });

  it('falls back to a safe enum value instead of rendering an unknown one', () => {
    const parsed = parseIntelligenceSnapshot({
      ...validSnapshot,
      signals: [{ ...validSnapshot.signals[0], kind: 'made_up', direction: 'sideways', confidence: 'total' }],
    })!;
    expect(parsed.signals[0]!.kind).toBe('no_change');
    expect(parsed.signals[0]!.direction).toBe('flat');
    expect(parsed.signals[0]!.confidence).toBe('low');
  });

  it('drops evidence entries with no fact path', () => {
    const parsed = parseIntelligenceSnapshot({
      ...validSnapshot,
      signals: [{ ...validSnapshot.signals[0], evidence: [{ metric: 'opens', value: 1 }] }],
    })!;
    expect(parsed.signals[0]!.evidence).toHaveLength(0);
  });

  it('parses each remaining payload kind and rejects junk', () => {
    expect(parseSignalSet({ periodLabel: 'p', summary: 's', signals: [], insufficientData: true })).not.toBeNull();
    expect(parseWeeklyReport({
      periodLabel: '2026-W33', headline: 'h', executiveSummary: 's',
      sections: [], recommendations: [], insufficientData: false, dataNotes: [],
    })).not.toBeNull();
    expect(parseGeneratedCopy({ headline: 'h', caption: 'c', hashtags: [], callToAction: 'x', factsUsed: [] })).not.toBeNull();
    expect(parseGeneratedCopy({ headline: 'h' })).toBeNull();
    expect(parseMarketingSuggestion({ propertyId: 'p1', angle: 'value', rationale: 'r', confidence: 'low', channels: [], copy: { headline: 'h', caption: 'c', hashtags: [], callToAction: 'x', factsUsed: [] } })).not.toBeNull();
    expect(parseAnswer({ answer: 'a', answered: true, evidence: [], followUps: [] })).not.toBeNull();
    expect(parseAnswer({ answered: true })).toBeNull();
  });

  it('rejects an artifact envelope whose payload fails validation', () => {
    expect(parseArtifact({
      id: 'a1', kind: 'intelligence_snapshot', periodKey: '2026-08-12',
      version: 1, schemaVersion: 'v1', generatedAt: '2026-08-12T00:00:00Z',
      payload: { nope: true },
    }, PAYLOAD_PARSERS.intelligence_snapshot)).toBeNull();
  });

  it('keeps provenance available for auditing', () => {
    const artifact = parseArtifact({
      id: 'a1', kind: 'intelligence_snapshot', periodKey: '2026-08-12',
      version: 2, schemaVersion: 'v1', generatedAt: '2026-08-12T00:00:00Z',
      payload: validSnapshot,
      provenance: { provider: 'openai', model: 'gpt-4.1-mini', contextDigest: 'a'.repeat(64) },
    }, PAYLOAD_PARSERS.intelligence_snapshot)!;
    expect(artifact.version).toBe(2);
    expect(artifact.provenance.provider).toBe('openai');
  });
});

/* ═══════════════════════════════════════════════════════════════
   6. FAILURE BOUNDARY
   ═══════════════════════════════════════════════════════════════ */

describe('AI failure never breaks a surface', () => {
  it('turns a thrown adapter into an unavailable value', async () => {
    const result = await withAiFallback(async () => { throw new Error('backend down'); });
    expect(result).toEqual({ kind: 'unavailable', reason: 'error' });
  });

  it('maps repository error codes onto availability reasons', async () => {
    expect(await withAiFallback(async () => err('unauthorized', 'x')))
      .toEqual({ kind: 'unavailable', reason: 'not_authenticated' });
    expect(await withAiFallback(async () => err('forbidden', 'x')))
      .toEqual({ kind: 'unavailable', reason: 'disabled' });
    expect(await withAiFallback(async () => err('rate_limited', 'x')))
      .toEqual({ kind: 'unavailable', reason: 'quota_exceeded' });
  });

  it('gives up rather than hanging a page', async () => {
    const result = await withAiFallback(
      () => new Promise(() => { /* never settles */ }),
      { timeoutMs: 20 },
    );
    expect(result.kind).toBe('unavailable');
  });

  it('passes a successful read straight through', async () => {
    const artifact = parseArtifact({
      id: 'a1', kind: 'intelligence_snapshot', periodKey: 'p', version: 1,
      schemaVersion: 'v1', generatedAt: '2026-08-12T00:00:00Z', payload: validSnapshot,
    }, PAYLOAD_PARSERS.intelligence_snapshot)!;
    const result = await withAiFallback(async () => ok({ kind: 'ready' as const, artifact }));
    expect(shouldRenderAi(result)).toBe(true);
  });

  it('does not render an unavailable value', () => {
    expect(shouldRenderAi(aiUnavailable('disabled'))).toBe(false);
  });

  it('flags an insufficient-data payload as a quiet state', () => {
    expect(isInsufficient({ insufficientData: true })).toBe(true);
    expect(isInsufficient(validSnapshot)).toBe(false);
    expect(isInsufficient(null)).toBe(false);
  });
});

/* ═══════════════════════════════════════════════════════════════
   7. MOCK MODE PRODUCES NO AI CONTENT
   ═══════════════════════════════════════════════════════════════ */

describe('mock AI repository', () => {
  const repository = new MockAiRepository();

  it('reports AI as disabled', async () => {
    const status = await repository.status();
    expect(status.ok && status.value).toEqual(AI_DISABLED_STATUS);
  });

  it('never fabricates an artifact', async () => {
    for (const read of [
      repository.snapshot(), repository.weeklyReport(),
      repository.signals(), repository.marketingSuggestion('prop-1'),
    ]) {
      const result = await read;
      expect(result.ok && result.value).toEqual({ kind: 'unavailable', reason: 'disabled' });
    }
  });

  it('returns no answer rather than an invented one', async () => {
    const answer = await repository.ask('what changed this week?');
    expect(answer.ok && answer.value).toBeNull();
  });

  it('returns empty operational lists', async () => {
    const usage = await repository.usage();
    expect(usage.ok && usage.value).toEqual([]);
    const actions = await repository.pendingActions();
    expect(actions.ok && actions.value).toEqual([]);
    const history = await repository.history('weekly_report');
    expect(history.ok && history.value).toEqual([]);
  });

  it('honours an abort signal like every other repository', async () => {
    const controller = new AbortController();
    controller.abort();
    const result = await repository.status({ signal: controller.signal });
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.error.code).toBe('aborted');
  });
});

/* ═══════════════════════════════════════════════════════════════
   8. COST MODEL
   ═══════════════════════════════════════════════════════════════ */

describe('cost formatting', () => {
  it('renders integer micro-USD as currency', () => {
    expect(formatMicroUsd(0)).toBe('$0.00');
    expect(formatMicroUsd(1_500_000)).toBe('$1.50');
    expect(formatMicroUsd(500)).toBe('<$0.01');
    expect(formatMicroUsd(-5)).toBe('$0.00');
  });
});

/* ═══════════════════════════════════════════════════════════════
   9. DATABASE SECURITY INVARIANTS
   ═══════════════════════════════════════════════════════════════ */

describe('AI migrations', () => {
  it('all ship as migration files', () => {
    for (const file of AI_MIGRATIONS) expect(existsSync(join(migrations, file))).toBe(true);
  });

  it('enables RLS on every new table', () => {
    const text = allAiSql();
    const created = [...text.matchAll(/create table if not exists public\.(\w+)/g)].map((m) => m[1]!);
    expect(created.length).toBeGreaterThan(8);
    for (const table of created) {
      expect(text, table).toContain(`alter table public.${table} enable row level security`);
    }
  });

  it('revokes direct table access from anon and authenticated', () => {
    const text = allAiSql();
    const created = [...text.matchAll(/create table if not exists public\.(\w+)/g)].map((m) => m[1]!);
    for (const table of created) {
      expect(text, table).toMatch(
        new RegExp(`revoke all on table public\\.${table} from public, anon, authenticated`),
      );
    }
  });

  it('scopes every dealer read policy to the caller\'s own dealer', () => {
    const text = allAiSql();
    const policies = [...text.matchAll(/create policy "[^"]+"\s*\non public\.\w+ for select to authenticated\s*\nusing \(([^;]+)\);/g)];
    expect(policies.length).toBeGreaterThan(8);
    for (const [, predicate] of policies) {
      expect(predicate).toContain('plotmap_current_dealer_id()');
      expect(predicate).toContain('plotmap_is_active_member()');
    }
  });

  it('keeps every dealer-id-taking RPC away from browser sessions', () => {
    const text = allAiSql();
    // These accept an explicit dealer id, so they must be service-role only.
    for (const fn of [
      'plotmap_ai_context_facts_for', 'plotmap_ai_marketing_facts_for',
      'plotmap_ai_enqueue_job', 'plotmap_ai_claim_jobs', 'plotmap_ai_start_execution',
      'plotmap_ai_store_artifact', 'plotmap_ai_propose_action', 'plotmap_ai_enabled_dealers',
    ]) {
      expect(text, fn).toMatch(new RegExp(`revoke all on function public\\.${fn}\\([^)]*\\) from public, anon, authenticated`));
      expect(text, fn).toMatch(new RegExp(`grant execute on function public\\.${fn}\\([^)]*\\) to service_role`));
      expect(text, fn).not.toMatch(new RegExp(`grant execute on function public\\.${fn}\\([^)]*\\) to authenticated`));
    }
  });

  it('defaults AI to off for every dealer', () => {
    expect(sql(AI_MIGRATIONS[0]!)).toMatch(/ai_enabled boolean not null default false/);
  });

  it('cannot mark an external action as approval-free', () => {
    expect(sql(AI_MIGRATIONS[1]!)).toMatch(
      /check \(risk = 'internal' or requires_approval = true\)/,
    );
  });

  it('shows dealers only published artifacts', () => {
    expect(sql(AI_MIGRATIONS[1]!)).toMatch(/ai artifacts dealer read[\s\S]{0,300}status = 'published'/);
  });

  it('never stores a channel credential, only a reference', () => {
    const marketing = sql(AI_MIGRATIONS[3]!);
    expect(marketing).toContain('credential_ref');
    expect(marketing).not.toMatch(/access_token|refresh_token|client_secret/);
    // credential_ref is excluded from the browser-readable column grant.
    const grant = /grant select \(([\s\S]*?)\) on table public\.marketing_channel_accounts/.exec(marketing)?.[1] ?? '';
    expect(grant).not.toContain('credential_ref');
  });

  it('purges every AI and marketing table when a dealer is deleted', () => {
    const marketing = sql(AI_MIGRATIONS[3]!);
    for (const table of [
      'ai_settings', 'ai_quotas', 'ai_jobs', 'ai_executions', 'ai_usage_daily',
      'ai_artifacts', 'ai_action_proposals', 'ai_action_audit',
      'marketing_content_contexts', 'marketing_creatives', 'marketing_schedule_items',
      'marketing_publications', 'marketing_channel_accounts', 'external_performance_metrics',
    ]) {
      expect(marketing, table).toMatch(new RegExp(`'${table}'`));
    }
  });
});

describe('context builder privacy', () => {
  const text = sql(AI_MIGRATIONS[2]!);

  it('derives the tenant from the session, never from an argument', () => {
    expect(text).toMatch(/create or replace function public\.plotmap_ai_context_facts\(\s*\n?\s*p_window_days/);
    expect(text).toContain('v_dealer text := public.plotmap_current_dealer_id();');
  });

  it('states that presentation and link activity is anonymous', () => {
    expect(text).toContain("'presentationVisitorsIdentified', false");
    expect(text).toContain("'clientLinkVisitorsIdentified', false");
  });

  it('projects no customer, owner or token field', () => {
    for (const forbidden of [
      "payload->>'owner'", "payload->>'sellerPhone'", "payload->>'note'",
      'token_hash', 'token_hint', 'l.label', 'l.client_id',
    ]) {
      expect(text, forbidden).not.toContain(forbidden);
    }
  });

  it('uses the session hash only to count distinct sessions, never emits it', () => {
    expect(text).toContain('count(distinct e.session_hash)');
    // The hash appears in no jsonb_build_object output key.
    expect(text).not.toMatch(/'session[A-Za-z]*',\s*[a-z_.]*session_hash/i);
    expect(text).not.toMatch(/'sessionHash'/);
  });

  it('bounds every projected array', () => {
    expect((text.match(/limit v_top/g) ?? []).length).toBeGreaterThanOrEqual(10);
  });

  it('reads jsonb payload flags without a cast that a bad row could break', () => {
    expect(text).not.toMatch(/payload->>'published'\)::boolean/);
    expect(text).not.toMatch(/payload->>'sold'\)::boolean/);
    expect(text).toContain("(r.payload->'published') = 'true'::jsonb");
  });
});

/* ═══════════════════════════════════════════════════════════════
   10. EDGE SURFACE
   ═══════════════════════════════════════════════════════════════ */

describe('Edge functions', () => {
  const worker = readFileSync(join(repoRoot, 'supabase/functions/ai-worker/index.ts'), 'utf8');
  const run = readFileSync(join(repoRoot, 'supabase/functions/ai-run/index.ts'), 'utf8');

  it('the worker refuses to run without its shared secret', () => {
    expect(worker).toContain("if (!WORKER_KEY) return json({ ok: false, reason: 'worker_not_configured' }");
    expect(worker).toContain("secretMatches(request.headers.get('x-mapco-worker-key'), WORKER_KEY)");
  });

  it('the interactive surface never trusts a caller-supplied dealer id', () => {
    expect(run).toContain("rpc<AiStatus>('plotmap_ai_status', {}, { accessToken: caller.accessToken })");
    expect(run).not.toMatch(/body\.dealerId|body\.dealer_id/);
  });

  it('the interactive surface enforces an origin allow-list and a session', () => {
    expect(run).toContain('ORIGINS.has(clean)');
    expect(run).toContain('resolveCaller(request)');
  });

  it('marks an approved action with no executor as failed, never as done', () => {
    expect(worker).toContain('executor_not_registered');
    expect(worker).toMatch(/p_status: 'failed',\s*\n\s*p_error_message: 'executor_not_registered'/);
  });

  it('reports unimplemented pipelines as skipped with a reason', () => {
    expect(worker).toContain("return { status: 'skipped', reason: 'pipeline_not_implemented' }");
  });
});

describe('route entry', () => {
  it('the AI console is wired into the build', () => {
    expect(existsSync(join(v2Root, 'admin/ai-console.html'))).toBe(true);
    expect(readFileSync(join(v2Root, 'vite.config.ts'), 'utf8')).toContain('admin/ai-console.html');
  });
});
