// @vitest-environment jsdom
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { mountFounderControl } from '../src/apps/developer/view';
import type { founderRepository } from '../src/apps/developer/repository';
import type { DealerAccount, FounderWorkspace } from '../src/apps/developer/domain';
const dealer: DealerAccount = { dealer_id:'dealer-a',brand_name:'Real dealer',owner_name:null,owner_phone:null,login_email:'dealer@example.test',primary_area:'Mohali',account_status:'active',subscription_status:'trial',trial_start:'2026-09-10T00:00:00Z',trial_end:'2099-09-17T00:00:00Z',expiry_date:null,plan_code:null,paid:false,max_devices_allowed:4,approved_device_count:0,developer_notes:null,payment_notes:null };
const workspace: FounderWorkspace = { trials:[],evidence:[],predictions:[],devices:[],usage:{totalEvents:0,activeDays:0,events7d:0,lastActive:null},milestones:[],buyer:[],history:[] };
const tick = () => new Promise(resolve=>setTimeout(resolve,0));
let root: HTMLElement; let repo: typeof founderRepository;
beforeEach(()=>{document.body.innerHTML='<div id="app"></div>';root=document.querySelector('#app')!;repo={provisionDealer:vi.fn(),bootstrap:vi.fn().mockResolvedValue(true),dealers:vi.fn().mockResolvedValue([dealer]),workspace:vi.fn().mockResolvedValue(workspace),setAccount:vi.fn().mockResolvedValue(undefined),setDeviceStatus:vi.fn().mockResolvedValue(undefined),setDeviceLimit:vi.fn().mockResolvedValue(undefined),createActivationCode:vi.fn().mockResolvedValue({code:'01234567',expires_at:'2099-09-17T00:00:00Z'}),addEvidence:vi.fn().mockResolvedValue(undefined),addPrediction:vi.fn().mockResolvedValue(undefined),resolvePrediction:vi.fn().mockResolvedValue(undefined)};});
function click(selector: string){root.querySelector<HTMLButtonElement>(selector)!.click();}
function paidForm(){const form=root.querySelector<HTMLFormElement>('[data-form=paid]')!;(form.elements.namedItem('plan') as HTMLInputElement).value='Monthly';(form.elements.namedItem('through') as HTMLInputElement).value='2099-10-10';(form.elements.namedItem('amount') as HTMLInputElement).value='1250.50';return form;}
describe('Founder Control persistence boundary',()=>{
  it('renders real directory results and filters without creating dealer fixtures',async()=>{await mountFounderControl(root,repo,vi.fn());expect(root.textContent).toContain('Real dealer');expect(root.textContent).not.toContain('Sethi Real Estate');const input=root.querySelector<HTMLInputElement>('[data-search]')!;input.value='missing';input.dispatchEvent(new Event('input',{bubbles:true}));expect(root.querySelector('[data-roster]')!.textContent).toContain('No matching dealers');});
  it('keeps failed account writes visible and retains form values',async()=>{vi.mocked(repo.setAccount).mockRejectedValue(new Error('Backend denied the update'));await mountFounderControl(root,repo,vi.fn());paidForm().dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await tick();expect(root.querySelector('[role=alert]')!.textContent).toContain('Backend denied');expect(root.querySelector<HTMLElement>('[role=status]')!.hidden).toBe(true);expect((root.querySelector('[name=plan]') as HTMLInputElement).value).toBe('Monthly');expect(repo.dealers).toHaveBeenCalledTimes(1);});
  it('waits for saved backend state before success, then reloads the same tenant',async()=>{let finish!:()=>void;vi.mocked(repo.setAccount).mockImplementation(()=>new Promise<void>(resolve=>{finish=resolve;}));await mountFounderControl(root,repo,vi.fn());paidForm().dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));expect(root.querySelector<HTMLElement>('[role=status]')!.hidden).toBe(true);expect(repo.setAccount).toHaveBeenCalledWith({dealerId:'dealer-a',action:'paid',expiresAt:'2099-10-10T18:29:59.999Z',plan:'Monthly',paymentNote:'',amountPaise:125050});finish();await tick();expect(repo.workspace).toHaveBeenLastCalledWith('dealer-a');expect(root.querySelector('[role=status]')!.textContent).toContain('Saved to MAPCO');});
  it('distinguishes a saved mutation followed by a failed reload',async()=>{await mountFounderControl(root,repo,vi.fn());vi.mocked(repo.workspace).mockRejectedValue(new Error('Network interrupted'));paidForm().dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await tick();expect(root.querySelector('[role=alert]')!.textContent).toContain('Saved, but');expect(root.querySelector<HTMLElement>('[role=status]')!.hidden).toBe(true);});
  it('does not let a late response replace another selected dealer',async()=>{let late!:(value:FounderWorkspace)=>void;vi.mocked(repo.dealers).mockResolvedValue([dealer,{...dealer,dealer_id:'dealer-b',brand_name:'Second dealer'}]);await mountFounderControl(root,repo,vi.fn());vi.mocked(repo.workspace).mockImplementation(id=>id==='dealer-a'?new Promise(resolve=>{late=resolve;}):Promise.resolve(workspace));click('[data-dealer=dealer-a]');click('[data-dealer=dealer-b]');await tick();late(workspace);await tick();expect(root.querySelector('[data-workspace] h2')!.textContent).toBe('Second dealer');});
  it('keeps codes transient and safely renders untrusted dealer names',async()=>{vi.mocked(repo.dealers).mockResolvedValue([{...dealer,brand_name:'<img src=x onerror=alert(1)>'}]);await mountFounderControl(root,repo,vi.fn());expect(root.querySelector('img')).toBeNull();click('[data-tab=Devices]');click('[data-code]');await tick();expect(root.querySelector('code')!.textContent).toBe('01234567');click('[data-dismiss-code]');expect(root.querySelector('code')).toBeNull();expect(localStorage.length).toBe(0);});
});
