import { accountState, escapeHtml as h, formatDate, type DealerAccount, type FounderWorkspace } from './domain';
export const tabs = ['Account', 'Devices', 'Usage', 'Evidence', 'Predictions', 'History'] as const;
export type Tab = typeof tabs[number];
export const options = (values: readonly string[]) => values.map(v => `<option value="${h(v)}">${h(v.replaceAll('_',' '))}</option>`).join('');
const date = (value: string | null | undefined) => h(formatDate(value));
const stat = (label: string, value: unknown) => `<div class="fc-stat">${h(label)}<strong>${h(value ?? 'Not recorded')}</strong></div>`;
const trialSelect = (w: FounderWorkspace) => `<label>Related trial<select name="trial"><option value="">Dealer account overall</option>${w.trials.map(t => `<option value="${h(t.id)}">${date(t.started_at)} · ${h(t.commercial_outcome)}</option>`).join('')}</select></label>`;

export function workspaceHtml(d: DealerAccount,w: FounderWorkspace,tab: Tab): string {
  const header = `<section><h2>${h(d.brand_name)}</h2><small>${h(d.dealer_id)}</small><nav aria-label="Dealer workspace">${tabs.map(t => `<button data-tab="${t}" aria-pressed="${tab===t}">${t}</button>`).join('')}</nav></section>`;
  let content: string;
  switch(tab) {
    case 'Account': content = `<section><h3>Account access</h3><div class="fc-grid">${stat('Current status',accountState(d))}${stat('Approved devices',`${d.approved_device_count} / ${d.max_devices_allowed}`)}</div><p>Access ends: ${date(d.subscription_status==='trial'?d.trial_end:d.expiry_date)} · Times shown in India time.</p><p>${h(d.login_email || 'Login email not recorded')}<br>${h(d.owner_name || 'Owner not recorded')} · ${h(d.owner_phone || 'Phone not recorded')}</p><button class="${d.account_status==='suspended'?'secondary':'danger'}" data-account-action="${d.account_status==='suspended'?'resume':'suspend'}">${d.account_status==='suspended'?'Restore account access':'Suspend dealer access'}</button></section>
      <section><h3>Record paid access</h3><p>After collecting payment, set the last day of access. The same dealer account and its existing data are retained.</p><form data-form="paid"><div class="fc-grid"><label>Plan name<input name="plan" required maxlength="80" value="${h(d.plan_code)}"></label><label>Active through (India time)<input name="through" type="date" required></label><label>Amount collected (₹, optional)<input name="amount" type="number" min="0" step="0.01"></label></div><label>Payment note<textarea name="note" maxlength="2000">${h(d.payment_notes)}</textarea></label><button>Save paid access</button></form></section>
      ${d.subscription_status==='trial'?'<section><h3>Extend this trial</h3><form data-form="extend_trial"><label>Active through (India time)<input type="date" name="through" required></label><button>Save trial extension</button></form></section>':''}`; break;
    case 'Devices': content = `<section><h3>Approved devices</h3><p>One 8-digit code approves one browser installation. Signing out keeps its approval. You manage all replacements.</p><button data-code>Create activation code</button><div data-code-result></div><form data-form="device_limit"><label>Device limit<input name="limit" type="number" min="1" max="20" step="1" required value="${h(d.max_devices_allowed)}"></label><button class="secondary">Save limit</button></form>${w.devices.map(device => `<div class="fc-item"><strong>${h(device.device_label || 'Unnamed device')}</strong><small>${h(device.browser_info || 'Browser not recorded')}</small><p>${h(device.status)} · Last used ${date(device.last_seen)}</p>${device.status==='approved'?`<button class="danger" data-revoke="${h(device.id)}">Revoke approval</button>`:''}</div>`).join('') || '<p>No devices recorded.</p>'}</section>`; break;
    case 'Usage': {
      const total = (key: 'opens'|'intent_actions'|'visit_requests') => w.buyer.reduce((sum,b)=>sum+Number(b[key]),0);
      content = `<section><h3>Observed dealer activity</h3><div class="fc-grid">${stat('Recorded events',w.usage.totalEvents)}${stat('Active days',w.usage.activeDays)}${stat('Events in 7 days',w.usage.events7d)}</div><p>Last activity: ${date(w.usage.lastActive)}</p></section><section><h3>Buyer activity</h3><p>Recorded buyer interactions are separate from a payment or conversion.</p><div class="fc-grid">${stat('Link opens',total('opens'))}${stat('Intent actions',total('intent_actions'))}${stat('Visit requests',total('visit_requests'))}</div></section><section><h3>Trial progression</h3>${w.trials.map(t => {const m=w.milestones.find(row=>row.trial_id===t.id);return `<div class="fc-item"><strong>${date(t.started_at)} → ${date(t.ends_at)}</strong><p>Commercial outcome: ${h(t.commercial_outcome)} · Source: ${h(t.acquisition_source)}</p>${m?`<div class="fc-grid">${stat('Properties saved',m.properties_added)}${stat('Failed property saves',m.property_add_failures)}${stat('Active days',m.active_days)}</div><p>First client link: ${date(m.first_link_at)}</p>`:'<p>No trial progression recorded.</p>'}</div>`;}).join('') || '<p>No structured trial history recorded for this account.</p>'}</section>`; break;
    }
    case 'Evidence': content = `<section><h3>Record evidence</h3><form data-form="evidence"><div class="fc-grid"><label>Kind<select name="kind">${options(['objection','statement','intervention','surprise','decision','treatment_change'])}</select></label><label>Source<select name="provenance">${options(['founder_observed','dealer_stated','buyer_observed','backfilled'])}</select></label></div>${trialSelect(w)}<label>When it happened (local time)<input type="datetime-local" name="occurred" required></label><label>What happened<textarea name="body" required maxlength="4000"></textarea></label><button>Save evidence</button></form></section><section><h3>Evidence journal</h3><p>Latest 200 records. Observations retain their source.</p>${w.evidence.map(e=>`<article class="fc-item"><strong>${h(e.kind.replaceAll('_',' '))} · ${h(e.provenance.replaceAll('_',' '))}</strong><small>${date(e.occurred_at)}</small><p>${h(e.body)}</p></article>`).join('') || '<p>No evidence recorded yet.</p>'}</section>`; break;
    case 'Predictions': content = `<section><h3>Make a prediction</h3><p>The statement, confidence and deadline stay fixed after saving. Record the actual outcome later.</p><form data-form="prediction">${trialSelect(w)}<label>Prediction<textarea name="statement" required maxlength="500"></textarea></label><div class="fc-grid"><label>Domain<select name="domain">${options(['pricing','product','behaviour','timing','commercial','other'])}</select></label><label>Confidence (%)<input name="confidence" type="number" min="1" max="99" required></label><label>Deadline (local time)<input name="horizon" type="datetime-local" required></label></div><button>Save prediction</button></form></section><section><h3>Predictions and outcomes</h3><p>Latest 200 records.</p>${w.predictions.map(p=>`<article class="fc-item"><strong>${h(p.statement)}</strong><p>${h(p.confidence)}% · ${h(p.domain)} · Due ${date(p.horizon_at)} · ${h(p.resolution)}</p>${p.resolution==='pending'?`<details><summary>Record outcome</summary><form data-form="resolve" data-id="${h(p.id)}"><label>Outcome<select name="resolution">${options(['true','false','unresolvable','expired'])}</select></label><label>Supporting evidence<textarea name="note" required maxlength="4000"></textarea></label><button>Save outcome</button></form></details>`:`<p>${h(p.resolution_note)}</p>`}</article>`).join('') || '<p>No predictions recorded yet.</p>'}</section>`; break;
    case 'History': content = `<section><h3>Account history</h3><p>Latest 100 administrative events.</p>${w.history.map(e=>`<article class="fc-item"><strong>${h(e.action_type.replaceAll('_',' '))}</strong><small>${date(e.created_at)}</small><p>${h(Object.entries(e.metadata??{}).map(([key,value])=>`${key}: ${String(value)}`).join('\n'))}</p></article>`).join('') || '<p>No administrative events recorded.</p>'}</section>`;
  }
  return header+content;
}
